// GENERATED by scripts/gen-ios-demo-list.mjs — do not edit by hand.
// Source of truth: scripts/demo-data.mjs. Re-run the generator to update.

struct DemoClient {
    let id: String
    let slug: String
    let appName: String
    let businessName: String
    let tagline: String
    let primaryColorHex: String
}

let demoClients: [DemoClient] = [
    DemoClient(id: "d0d00000-0000-0000-0000-000000000001", slug: "demo-salon", appName: "Fern & Fox", businessName: "Fern & Fox Hair Studio", tagline: "Colour, cuts & care in the heart of Riverdale", primaryColorHex: "#6b3f5b"),
    DemoClient(id: "d0d00000-0000-0000-0000-000000000002", slug: "demo-trades", appName: "Rivertown Plumbing", businessName: "Rivertown Plumbing & Heating", tagline: "Licensed plumbing & heating, on time or it’s free", primaryColorHex: "#1d4e89"),
    DemoClient(id: "d0d00000-0000-0000-0000-000000000003", slug: "demo-maker", appName: "Ember Hot Sauce", businessName: "Ember Hot Sauce Co.", tagline: "Small-batch heat, made in Montréal", primaryColorHex: "#9c2b1b"),
    DemoClient(id: "d0d00000-0000-0000-0000-000000000004", slug: "demo-popup", appName: "Bloom Cart", businessName: "Bloom Cart Flowers", tagline: "A flower cart that finds you", primaryColorHex: "#b14a7a"),
    DemoClient(id: "d0d00000-0000-0000-0000-000000000005", slug: "demo-pet", appName: "Wag & Wash", businessName: "Wag & Wash Mobile Grooming", tagline: "The spa that comes to your driveway", primaryColorHex: "#0f766e"),
    DemoClient(id: "d0d00000-0000-0000-0000-000000000006", slug: "demo-vehicle", appName: "Apex Detailing", businessName: "Apex Mobile Detailing", tagline: "Showroom shine, in your driveway", primaryColorHex: "#1f2933"),
    DemoClient(id: "d0d00000-0000-0000-0000-000000000007", slug: "demo-creative", appName: "Northlight", businessName: "Northlight Photography", tagline: "Weddings, portraits & brand stories", primaryColorHex: "#2b2b2b"),
    DemoClient(id: "d0d00000-0000-0000-0000-000000000008", slug: "demo-education", appName: "Keynote Music", businessName: "Keynote Music Lessons", tagline: "Piano, guitar & voice — all ages", primaryColorHex: "#1e3a5f"),
    DemoClient(id: "d0d00000-0000-0000-0000-000000000009", slug: "demo-health", appName: "Stillwater RMT", businessName: "Stillwater Massage Therapy", tagline: "Registered massage therapy — direct billing", primaryColorHex: "#4a6b57"),
    DemoClient(id: "d0d00000-0000-0000-0000-00000000000a", slug: "demo-retail", appName: "Marigold", businessName: "Marigold Home Goods", tagline: "Curated home goods & gifts", primaryColorHex: "#b4552d"),
    DemoClient(id: "d0d00000-0000-0000-0000-00000000000b", slug: "demo-pro", appName: "Ledger & Co.", businessName: "Ledger & Co. Bookkeeping", tagline: "Bookkeeping & tax prep for small business", primaryColorHex: "#12433a"),
    DemoClient(id: "d0d00000-0000-0000-0000-00000000000c", slug: "demo-property", appName: "Greenfield", businessName: "Greenfield Lawn & Snow", tagline: "Lawn care in summer, snow clearing all winter", primaryColorHex: "#2f5d34"),
]
